source ~/.zshenv

source $HOME/.dotfiles/zsh/antigen.zsh

# Load oh-my-zsh library
#antigen use oh-my-zsh

# Add bundles
# Local bundles
antigen bundle $HOME/.dotfiles/zsh plugins/git
antigen bundle $HOME/.dotfiles/zsh plugins/docker-compose-shortcuts
antigen bundle $HOME/.dotfiles/zsh plugins/curl
antigen bundle $HOME/.dotfiles/zsh plugins/ruby
antigen bundle $HOME/.dotfiles/zsh plugins/nodejs
antigen bundle $HOME/.dotfiles/zsh plugins/tmuxinator
antigen bundle $HOME/.dotfiles/zsh plugins/macbuntu

# Keep 1000 lines of history within the shell and save it to ~/.zsh_history:
HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.zsh_history


# Syntax highlighting
antigen bundle zsh-users/zsh-syntax-highlighting

# Autocompletion
antigen bundle zsh-users/zsh-autosuggestions

# Theme
antigen theme https://github.com/denysdovhan/spaceship-prompt spaceship


# Done
antigen apply

SPACESHIP_CHAR_SYMBOL="▶ "

SPACESHIP_PROMPT_ORDER=(
  time          # Time stamps section
  user          # Username section
  dir           # Current directory section
  host          # Hostname section
  git_branch
  exec_time     # Execution time
  line_sep      # Line break
  jobs          # Background jobs indicator
  exit_code     # Exit code section
  char          # Prompt character
)

export PGHOST=localhost
export PGUSER=postgres
export EDITOR=vim

export PATH="$HOME/.dotfiles/bin:$PATH"
