source ~/.zshenv

source $HOME/.dotfiles/zsh/antigen.zsh

# Load oh-my-zsh library
#antigen use oh-my-zsh

# Add bundles
# Local bundles
antigen bundle $HOME/.dotfiles/zsh plugins/git
antigen bundle $HOME/.dotfiles/zsh plugins/docker-compose-shortcuts
antigen bundle $HOME/.dotfiles/zsh plugins/curl
antigen bundle $HOME/.dotfiles/zsh plugins/asdf
antigen bundle $HOME/.dotfiles/zsh plugins/tmuxinator
antigen bundle $HOME/.dotfiles/zsh plugins/macbuntu

# Keep 1000 lines of history within the shell and save it to ~/.zsh_history:
HISTSIZE=1000
SAVEHIST=1000
HISTFILE=~/.zsh_history


# Syntax highlighting
antigen bundle zsh-users/zsh-syntax-highlighting

# Autocompletion
antigen bundle zsh-users/zsh-autosuggestions

# Theme
antigen theme https://github.com/denysdovhan/spaceship-prompt spaceship


# Done
antigen apply

SPACESHIP_CHAR_SYMBOL="▶ "

SPACESHIP_PROMPT_ORDER=(
  time          # Time stamps section
  user          # Username section
  dir           # Current directory section
  host          # Hostname section
  git_branch
  exec_time     # Execution time
  line_sep      # Line break
  jobs          # Background jobs indicator
  exit_code     # Exit code section
  char          # Prompt character
)

export PGHOST=localhost
export PGUSER=postgres
export EDITOR=vim

export PATH="$HOME/.dotfiles/bin:$PATH"

# tabtab source for serverless package
# uninstall by removing these lines or running `tabtab uninstall serverless`
[[ -f /home/josh/.nvm/versions/node/v10.16.0/lib/node_modules/serverless/node_modules/tabtab/.completions/serverless.zsh ]] && . /home/josh/.nvm/versions/node/v10.16.0/lib/node_modules/serverless/node_modules/tabtab/.completions/serverless.zsh
# tabtab source for sls package
# uninstall by removing these lines or running `tabtab uninstall sls`
[[ -f /home/josh/.nvm/versions/node/v10.16.0/lib/node_modules/serverless/node_modules/tabtab/.completions/sls.zsh ]] && . /home/josh/.nvm/versions/node/v10.16.0/lib/node_modules/serverless/node_modules/tabtab/.completions/sls.zsh
# tabtab source for slss package
# uninstall by removing these lines or running `tabtab uninstall slss`
[[ -f /home/josh/.nvm/versions/node/v10.16.0/lib/node_modules/serverless/node_modules/tabtab/.completions/slss.zsh ]] && . /home/josh/.nvm/versions/node/v10.16.0/lib/node_modules/serverless/node_modules/tabtab/.completions/slss.zsh

if command -v tmux &> /dev/null && [ -n "$PS1" ] && [[ ! "$TERM" =~ screen ]] && [[ ! "$TERM" =~ tmux ]] && [ -z "$TMUX" ]; then
  exec tmux new-session -A -s main
fi
